// codegen:start {preset: barrel, include: ./operations/*.ts, prefix: "@effect/query/DataSource"}
export * from "@effect/query/DataSource/operations/batchN"
export * from "@effect/query/DataSource/operations/contramap"
export * from "@effect/query/DataSource/operations/contramapEffect"
export * from "@effect/query/DataSource/operations/eitherWith"
export * from "@effect/query/DataSource/operations/equals"
export * from "@effect/query/DataSource/operations/fromFunction"
export * from "@effect/query/DataSource/operations/fromFunctionBatched"
export * from "@effect/query/DataSource/operations/fromFunctionBatchedEffect"
export * from "@effect/query/DataSource/operations/fromFunctionBatchedMaybe"
export * from "@effect/query/DataSource/operations/fromFunctionBatchedMaybeEffect"
export * from "@effect/query/DataSource/operations/fromFunctionBatchedWith"
export * from "@effect/query/DataSource/operations/fromFunctionBatchedWithEffect"
export * from "@effect/query/DataSource/operations/fromFunctionEffect"
export * from "@effect/query/DataSource/operations/fromFunctionMaybe"
export * from "@effect/query/DataSource/operations/fromFunctionMaybeEffect"
export * from "@effect/query/DataSource/operations/make"
export * from "@effect/query/DataSource/operations/makeBatched"
export * from "@effect/query/DataSource/operations/never"
export * from "@effect/query/DataSource/operations/provideEnvironment"
export * from "@effect/query/DataSource/operations/provideSomeEnvironment"
export * from "@effect/query/DataSource/operations/race"
// codegen:end
